triggers:
   - name: rs-tg1
     type: trigger
     version:
       counter: 0
       
   - name: rs-tg2
     type: trigger
     version:
       counter: 3
       
   - name: rs-tg3
     type: trigger
     version:
       counter: 1
